apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: invoices-microservice-seller-secret
  namespace: statex-apps
  labels:
    app: invoices-microservice
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: invoices-microservice-seller-secret
    creationPolicy: Owner
  data:
    - secretKey: INVOICE_SELLER_NAME
      remoteRef:
        key: secret/prod/invoices-microservice-seller
        property: INVOICE_SELLER_NAME
    - secretKey: INVOICE_SELLER_ADDRESS
      remoteRef:
        key: secret/prod/invoices-microservice-seller
        property: INVOICE_SELLER_ADDRESS
    - secretKey: INVOICE_SELLER_COMPANY_ID
      remoteRef:
        key: secret/prod/invoices-microservice-seller
        property: INVOICE_SELLER_COMPANY_ID
    - secretKey: INVOICE_SELLER_TAX_ID
      remoteRef:
        key: secret/prod/invoices-microservice-seller
        property: INVOICE_SELLER_TAX_ID
    - secretKey: INVOICE_SELLER_VAT_ID
      remoteRef:
        key: secret/prod/invoices-microservice-seller
        property: INVOICE_SELLER_VAT_ID
    - secretKey: INVOICE_SELLER_EMAIL
      remoteRef:
        key: secret/prod/invoices-microservice-seller
        property: INVOICE_SELLER_EMAIL
